name: API CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'surprizen-api/**'
      - '.github/workflows/api.yml'
  pull_request:
    branches: [main]
    paths:
      - 'surprizen-api/**'
      - '.github/workflows/api.yml'

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./surprizen-api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './surprizen-api/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Format check
        run: npx prettier --check "src/**/*.ts"

      - name: Type check
        run: npx tsc --noEmit

  deploy-cloud-run:
    name: Deploy to Cloud Run
    needs: lint-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/surprizen-api:${{ github.sha }} ./surprizen-api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy surprizen-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/surprizen-api:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars="NODE_ENV=production" \
            --min-instances=0 \
            --max-instances=10